# Generated by Django 4.2.5 on 2024-03-12 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookstoremodel',
            name='category',
            field=models.CharField(choices=[('Educational', 'Educational'), ('Thriller', 'Thriller'), ('Sci-fi', 'Sci-fi'), ('Romantic', 'Romantic'), ('Commics', 'Commics')], max_length=30),
        ),
        migrations.AlterField(
            model_name='bookstoremodel',
            name='last_pub',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
