# Generated by Django 4.2.5 on 2024-03-12 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_bookstoremodel_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookstoremodel',
            name='category',
            field=models.CharField(choices=[('Thriller', 'Thriller'), ('Comics', 'Comics'), ('Romantic', 'Romantic'), ('Educational', 'Educational'), ('Sci-fi', 'Sci-fi')], max_length=30),
        ),
    ]
