# Generated by Django 4.2.5 on 2024-03-08 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('roll', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=40)),
                ('subject_name', models.CharField(max_length=50)),
                ('college_name', models.CharField(max_length=50)),
                ('mobile', models.IntegerField(unique=True)),
            ],
        ),
    ]
